### ISSUE TITLE
Remove eval

### ISSUE THREAD

**Issue by rickyhan** [CityOfZion/neo-python#202]
https://github.com/CityOfZion/neo-python/blob/79770902337ced902513d59fa7a3453b81f987ca/neo/Prompt/Utils.py#L118

**Comment by Tommah** [comment]
I think that call to eval can be replaced with a call to ast.literal_eval.

This would almost work for the calls to eval in parse_param, but literal_eval cannot handle strings that contain a call to bytearray().

**Comment by dethos** [comment]
@localhuman is there a any spec of the content (and types) that should be allowed in the transaction attributes?

I ask this because for what I can see in the code examples (PR, tests and change log), this could be solved by providing a json `array` or `object` for this argument instead of the python `list` or `dict`. This way it would be saver to parse instead of using `eval`.

**Comment by localhuman** [comment]
That's a good idea.  I personally like the free form way, but we could do something like how the JSONRPC Api accepts contract parameters here:
https://github.com/CityOfZion/neo-python/blob/master/neo/api/JSONRPC/JsonRpcApi.py#L223

**Comment by ixje** [comment]
solved in above pr
