### ISSUE TITLE
Perhaps consider using a different web framework api?

### ISSUE THREAD

**Issue by jhwinter** [CityOfZion/neo-python#501]
Klein is consistently outperformed in almost every category by other Python web frameworks according to these benchmarks: https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=json&l=hr9ywv

**Comment by ixje** [comment]
We feel in no way attached to certain web frameworks and we're open to outside contributions. `Klein` was used due to being familiar with it and its simplicity. I don't think we've heard of performance issues  yet, but that does not mean we can't improve upfront. I hope you'll consider a contribution

**Comment by metachris** [comment]
We evaluated web frameworks, but neo-python is using twisted for all it's networking and event loop and Klein seems to be the best web framework for twisted. Adding tornado or something else would not be a good fit because everything is already built on twisted.

Thanks for the suggestion though! Closing this issue now.
