### ISSUE TITLE
[Feature] Prepare for PyPi

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#64]
- Prepare project to be published on PyPi
- Depends on #63

**Comment by metachris** [comment]
Not sure if you know [cookiecutter-pypackage](https://github.com/audreyr/cookiecutter-pypackage). I'm a big fan of the setup this produces, because it will, for instance, auto-release to PyPI when you push a new tag to master (optional), among other nice things. It also produces a nice Sphinx docs setup.

Perhaps worth to take a look and perhaps reuse some of the nicer parts.

**Comment by localhuman** [comment]
Awesome, will take a look!

**Comment by localhuman** [comment]
This is complete.
