### ISSUE TITLE
np-bootstrap -c configure my local sync node that haved sync and the block data is finish.

### ISSUE THREAD

**Issue by ai-chen2050** [CityOfZion/neo-python#971]
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
yes
- What is the problem?
np-bootstrap -c configure my local sync node that haved sync and the block data is finish.
I want to use my local config and data dir, But  I  meet this error. And My sync node had used
 the 20332 port
- Include a screenshot if it makes sense.

![image](https://user-images.githubusercontent.com/27693952/59997951-ca008700-9690-11e9-9f57-62a7779e771f.png)

![image](https://user-images.githubusercontent.com/27693952/59998176-5ca12600-9691-11e9-91b6-87f824c9b0a4.png)

### Expected behavior

- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
Ubuntu 16.04 
- neo-python version: (hint: use `np-prompt --version`)
lastest
- Python version: (hint: `python -V`)
3.7

**Comment by ixje** [comment]
> neo-python version: (hint: use np-prompt --version)
lastest

Next time be specific. Latest release (`0.8.4`)? latest development? 

It looks like you're trying to run development branch. Development branch cannot use `np-bootstrap` because the bootstrap files are not yet updated. If you read the error message you'll see that port 20333 is already in use. 2 possible reasons can be
1. you're running a private net (like [neo-private](https://hub.docker.com/r/cityofzion/neo-privatenet/) or neo-local) that already uses the 20333 port.
2. you have another neo-python or neo-cli instance running at the same port
